infisical secrets set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_dWx0aW1hdGUtZGluZ28tNDguY2xlcmsuYWNjb3VudHMuZGV2JA" --env=prod
infisical secrets set CLERK_SECRET_KEY="sk_test_cXoGaIXOhqS51WyKqdYRwXAExZieNQHloR7FmU7KtS" --env=prod
infisical secrets set SUPABASE_DATABASE_PASSWORD="EUYNUhtOrHJB5fbH" --env=prod
infisical secrets set VERCEL_API_KEY="vck_5rKEI13Y5zAlTLwNO5coMsHUnbTXsE8tn7sf2UPvjClrYggZuL2RezeJ" --env=prod
infisical secrets set COINBASE_CLIENT_API_KEY="bxVZm3yXCXhDJcJpjF0CzAJlocSDg6Zi" --env=prod
infisical secrets set COINBASE_API_KEY="b073f8a1-b2b6-485c-8876-cbf644f70aca" --env=prod
infisical secrets set COINBASE_SECRET_API_KEY="3rsunsMB1M61LU+AIi+vmnN4Qsli/jAfeaBk0ej+NlTW+SpsD0qAe1LnN2WETMe++jT2IdwXLClSRHWPho/f/A==" --env=prod
infisical secrets set ALCHEMY_ENDPOINT_URL="https://eth-mainnet.g.alchemy.com/v2/8VAudAmIHyQO0WW0xoenE" --env=prod
infisical secrets set ALCHEMY_API_KEY="8VAudAmIHyQO0WW0xoenE" --env=prod
infisical secrets set STRIPE_PUBLISHABLE_KEY="pk_test_51TYJq2J4IBsxckIQHOf5kkFTSHfh75jyReCgdyHoRplUl86b2umEDMcLMy9JWPUuS4Oq1D8XMkHNwiFwyMO6Bbvr00p4wT81b2" --env=prod
infisical secrets set STRIPE_SECRET_KEY="sk_test_51TYJq2J4IBsxckIQs7K2T9kDjtpNCHPWvUXqDCDUfCjhu46XXy9BOxltt0GZmYiX8XJTEOzTpcmdajNnm9J5guEv00Gfl4uaru" --env=prod
infisical secrets set STRIPE_RESTRICTED_KEY="rk_test_51TYJq2J4IBsxckIQPi7rvgzqeNxLr7Z8VaZmIN7FJ0HwOrSIqoyTp6E4dxcQTXnSznnCJZI5i1rP7ztLUX5LHY0800zdr8RL6A" --env=prod
infisical secrets set PLAID_CLIENT_ID="6a1ec4fcb033d9000d7b77dc" --env=prod
infisical secrets set PLAID_SANDBOX_SECRET="6a1ec4fcb033d9000d7b77dc" --env=prod
infisical secrets set GEMINI_API_KEY="AQ.Ab8RN6IzI_GYsWCqPqvvAxENOuU7ZxHYh7TF84rxuqaliXt7eA" --env=prod
infisical secrets set EXPO_API_KEY="PY-kXQr1NNzMzi2BhQXxTWP48E3nlx6e4dqmAWZU" --env=prod
infisical secrets set CLEO_ROBOT_API="FP4LFkJgOEP-9enMZ52CdxzvI8uKrfiAxiuEmQlU" --env=prod
infisical secrets set GOOGLE_DOMAINKEY="v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn15TO+SDlDkrJzyP4wM8zEPbH2MzF72mxC5jBFtoAebAFE89Z5n5X2c/XzMlsV9ECBtcHQSNDjKGRjC54nJ9O1PfqxD/CQjQqIhAY9CYhEw7TMM6PWpqxsoZEGYkSIXwu0YfWiUsqf93dnkePIbniiOY80voq2WgxdF2TuTjvQD6ii6BHolvQIEFQXuv3IovYQfLSSsfoVJyfVqhvIXZxkkVHIhlvMudi+grIMwVbRcQ1s2VbhVYY53DIgGHgqfr8+10sDXwz5cTTSWqWzoNmUEDXQ/aWuEijazTUWY88wtT6VdGkYGlPtYPqWA2pRedM//KCmjN0FT5MDmy+XV+fQIDAQAB" --env=prod
infisical secrets set ETHERSCAN_API_KEY="Z7E6J1HT1DM2FWZQ52CJVGSWEGGBKH7SET" --env=prod
infisical secrets set BASE_API_KEY="bdev_HeNYRcGoumNLrkaTfgIdxZp2-9SgGT-VoMw8_E2Z_VQ" --env=prod
