# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantumcoin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quantumcoin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11quantumcoin.proto\x12\x0bquantumcoin\"3\n\x0bQnrgRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62yte_length\x18\x02 \x01(\x05\"Z\n\x0cQnrgResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0brandom_seed\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65vice_used\x18\x04 \x01(\t2V\n\rQuantumEngine\x12\x45\n\x0cGenerateQnrg\x12\x18.quantumcoin.QnrgRequest\x1a\x19.quantumcoin.QnrgResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantumcoin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QNRGREQUEST']._serialized_start=34
  _globals['_QNRGREQUEST']._serialized_end=85
  _globals['_QNRGRESPONSE']._serialized_start=87
  _globals['_QNRGRESPONSE']._serialized_end=177
  _globals['_QUANTUMENGINE']._serialized_start=179
  _globals['_QUANTUMENGINE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
