# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quantumcoin_pb2 as quantumcoin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quantumcoin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantumEngineStub(object):
    """The Quantum Engine service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateQnrg = channel.unary_unary(
                '/quantumcoin.QuantumEngine/GenerateQnrg',
                request_serializer=quantumcoin__pb2.QnrgRequest.SerializeToString,
                response_deserializer=quantumcoin__pb2.QnrgResponse.FromString,
                _registered_method=True)


class QuantumEngineServicer(object):
    """The Quantum Engine service definition
    """

    def GenerateQnrg(self, request, context):
        """Generate Quantum Random Numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateQnrg': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQnrg,
                    request_deserializer=quantumcoin__pb2.QnrgRequest.FromString,
                    response_serializer=quantumcoin__pb2.QnrgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantumcoin.QuantumEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantumcoin.QuantumEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantumEngine(object):
    """The Quantum Engine service definition
    """

    @staticmethod
    def GenerateQnrg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantumcoin.QuantumEngine/GenerateQnrg',
            quantumcoin__pb2.QnrgRequest.SerializeToString,
            quantumcoin__pb2.QnrgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
