name: test

on:
  push:
    branches:
      - test-auto-healer

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Intentionally fail
        run: node scripts/fail.js
