import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import { RootProvider } from "./rootProvider";
import * as Sentry from "@sentry/nextjs";
import { ClerkProvider } from '@clerk/nextjs'
import { AlchemyProviderWrapper } from "./AlchemyProviderWrapper";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <html lang="en">
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <RootProvider>
          <Sentry.ErrorBoundary fallback={<p>An error has occurred.</p>}>
            {children}
          </Sentry.ErrorBoundary>
        </RootProvider>
      </body>
    </html>
  );

  // Security: Frontend bypass allowed ONLY if a matching bypass key is provided in the request header AND the environment.
  // We use the non-public BYPASS_AUTH_KEY to avoid leaking the secret to the client bundle.
  let isBypassed = false;
  try {
    const { headers } = require('next/headers');
    const headerList = headers();
    const bypassKey = process.env.BYPASS_AUTH_KEY;
    if (bypassKey && bypassKey.length > 0 && headerList.get('x-bypass-auth-key') === bypassKey) {
      isBypassed = true;
    }
  } catch (e) {
    // headers() might not be available at build time
  }

  if (isBypassed) {
    return content;
  }

  return (
    <ClerkProvider>
      <AlchemyProviderWrapper>
        {content}
      </AlchemyProviderWrapper>
    </ClerkProvider>
  );
}
