"""Exact reversible SHA-256 compiler for d=8 transmon packing."""

from .carrier_ir import (
    CarrierProgram,
    CrossCarrierGate,
    LocalPermutation8,
    compile_carrier_program,
    exact_local_permutation,
    simulate_carrier_program,
    verify_carrier_program,
)
from .coherent_dag import (
    BooleanDag,
    CoherentScheduleDag,
    ScheduleDagStats,
    build_schedule_dag,
    build_schedule_dag_candidates,
    select_schedule_dag,
)
from .coherent_pebble import (
    PebbleAction,
    WordPebbleProgram,
    execute_compute_use_uncompute,
    execute_word_program,
    plan_word_pebbles,
    sigma_maps_are_invertible,
)
from .coherent_program import (
    CircuitBlock,
    CompiledCoherentSha256,
    StreamedScheduleAdd,
    coherent_digest_words,
    coherent_initial_state,
    compile_coherent_nonce_sha256,
    lower_streamed_schedule_operation,
    simulate_coherent_operations,
    verify_compiled_coherent_sha256,
)
from .coherent_round16 import (
    CoherentRound16Schedule,
    CoherentRound64Schedule,
    CoherentRoundTerm,
    fuse_round_constant,
    plan_round16_schedule,
    plan_round64_schedule,
    plan_round_term,
    verify_round_term,
)
from .coherent_stream import (
    StreamedWordAddReport,
    emit_node_xor,
    emit_streamed_schedule_add,
    streamed_word_add_report,
)
from .coherent_schedule import (
    CoherentSchedulePlan,
    compress_reference,
    evaluate_schedule,
    plan_coherent_schedule,
)
from .layout import (
    D8Layout,
    available_coherent_layout_profiles,
    available_layout_profiles,
)
from .workspace_liveness import (
    WorkspaceLease,
    WorkspaceLivenessReport,
    analyze_workspace_liveness,
)
from .sha256 import compile_single_block_sha256, simulate_compiled_sha256

__all__ = [
    "BooleanDag",
    "verify_compiled_coherent_sha256",
    "simulate_coherent_operations",
    "lower_streamed_schedule_operation",
    "compile_coherent_nonce_sha256",
    "coherent_initial_state",
    "coherent_digest_words",
    "StreamedScheduleAdd",
    "CompiledCoherentSha256",
    "CircuitBlock",
    "streamed_word_add_report",
    "emit_streamed_schedule_add",
    "emit_node_xor",
    "StreamedWordAddReport",
    "verify_carrier_program",
    "simulate_carrier_program",
    "exact_local_permutation",
    "compile_carrier_program",
    "LocalPermutation8",
    "CrossCarrierGate",
    "CarrierProgram",
    "PebbleAction",
    "CoherentScheduleDag",
    "CoherentSchedulePlan",
    "CoherentRound16Schedule",
    "CoherentRound64Schedule",
    "CoherentRoundTerm",
    "D8Layout",
    "analyze_workspace_liveness",
    "WorkspaceLivenessReport",
    "WorkspaceLease",
    "ScheduleDagStats",
    "WordPebbleProgram",
    "available_coherent_layout_profiles",
    "available_layout_profiles",
    "build_schedule_dag",
    "select_schedule_dag",
    "build_schedule_dag_candidates",
    "compile_single_block_sha256",
    "compress_reference",
    "evaluate_schedule",
    "fuse_round_constant",
    "execute_compute_use_uncompute",
    "execute_word_program",
    "plan_coherent_schedule",
    "plan_round16_schedule",
    "plan_round64_schedule",
    "plan_round_term",
    "plan_word_pebbles",
    "sigma_maps_are_invertible",
    "simulate_compiled_sha256",
    "verify_round_term",
]
