name: Build and Test
on:
  pull_request: {}

jobs:
  test:
    name: Type Check and Test
    type: custom
    steps:
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npx tsc --noEmit
        workingDirectory: mobile

  build_development:
    name: Development Build
    type: build
    needs: [test]
    params:
      platform: all
      profile: development
